### ISSUE TITLE
How to use this library for RA8876?

### ISSUE THREAD

**Issue by momosh13** [wwatson4506/Ra8876LiteTeensy#1]
Hello.
Thank you for this library, i want to use this library with Teensy 3.2 to control RA8876 , but the screen showing crazy things. Example in graphics.ino  i'm commenting #include "Ra8876_Lite.h",
the example still compiling (no errors), so please help me, how i can run graphics.ino for RA8876?
not for tft.h or vt100.h?. 
Thank you

**Comment by wwatson4506** [comment]
Check out R8876LiteTeensy.cpp and .h. The tft.cpp and tft.h files contain wrapper functions for the lower level RA8876 driver.
What display are you using? This library was written for BuyDisplay's ER-TFTM101-1 10.1 inch lcd module tft display. That's the only TFT this library has been tested on. If you are using another size of TFT the video timings and external memory settings will be wrong. This might be why you are seeing what you are seeing on your display. Also check out line 844 in Ra8876Lite.h. This line sets the SPI clock speed. Try setting it to '_maxspeed = 20000000'. If that works then you can increase the setting until it causes your problem again.
Good luck.

**Comment by momosh13** [comment]
Thanks for your answer.
I figure out my display issue and now it is working as expected.
Thank you.
