### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by momosh13** [wwatson4506/Ra8876LiteTeensy#2]
Hello,
Recently I communicated with Mountain Hung from RAIO TECHNOLOGY INC. regarding adding rotation functions into his library.
He updated his library with rotation functions and sent it to me.
Is it possible that you check his new library and add same rotation functions into your's?
How I can upload new library here or send it to you directly?

Thanks.

**Comment by momosh13** [comment]
Hi
I just added it the rotation file from RAIO  to my GitHub,

https://github.com/momosh13/RA8876_Lite_Graphic_Rotate

Thank you

**Comment by wwatson4506** [comment]
Mountain Hung is very supportive. He provided me with several bug fixes and sample sketches. I'll check out the rotation sketch and update my driver. It may take a little while as I am busy with other project as well:)

**Comment by momosh13** [comment]
Hello
Just checking, you any good news for me?
Thank you
